service: session-store-node

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:BatchWriteItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
      Resource:
        - Fn::GetAtt:
          - SessionStoreTable
          - Arn
        - Fn::Join:
          - '/'
          - - Fn::GetAtt:
              - SessionStoreTable
              - Arn
            - "index"
            - "UserIndex"

  environment:
    TABLE_NAME: { Ref: SessionStoreTable }
    INDEX_NAME: 'UserIndex'

functions:
  createSession:
    handler: handlers/createSession.createSession
    events:
      - http:
          path: sessions
          method: post
  getSession:
    handler: handlers/getSession.getSession
    events:
      - http:
          path: sessions
          method: get
  deleteSessionsForUser:
    handler: handlers/deleteSessionsForUser.deleteSessionsForUser
    events:
      - http:
          path: sessions/{username}
          method: delete

resources:
  Resources:
    SessionStoreTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - AttributeName: "SessionId"
            AttributeType: "S"
          - AttributeName: "Username"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "SessionId"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        GlobalSecondaryIndexes: 
          - IndexName: "UserIndex"
            KeySchema: 
              - AttributeName: "Username"
                KeyType: "HASH"
            Projection:
              ProjectionType: "KEYS_ONLY"
        TimeToLiveSpecification:
          AttributeName: "TTL"
          Enabled: true