#!/usr/bin/env bash

if [[ ! -e ./build ]]; then
  mkdir ./build
fi

if [ "$1" != "" ]; then
  FILE_NAME=$(echo $1 | sed 's/\.[^.]*$//');
  g++-9 -std=c++2a -O2 -fconcepts -Wall -Wpedantic $1 -o ./build/$FILE_NAME && ./build/$FILE_NAME
else
  echo "Please provide a file to compile"
fi

